### ISSUE TITLE
When loss_layer_num>1, why just use one layer for the auxiliary loss?

### ISSUE THREAD

**Issue by ewrfcas** [IceTTTb/PlaneTR3D#2]
Thanks for your good works!
loss_layer_num is set as 3 in the config. But only layer[1] and layer[-1] are optimized?
https://github.com/IceTTTb/PlaneTR3D/blob/09b6df2e339bbadeb254af5c893174df0896353b/models/planeTR_HRNet.py#L347-L353

**Comment by IceTTTb** [comment]
@ewrfcas
Thank you for your interest in our work!
Our initial idea is to use the outputs from all three layers for training, but we find that only the last two layers are used in practice when we clean up the codes. To be consistent with the submitted results in the paper, we keep this setting in the public code.  We will update the code to make it clear.

**Comment by ewrfcas** [comment]
Thanks for your reply.
