### ISSUE TITLE
How to get the planes_scannet_train.tfrecords?

### ISSUE THREAD

**Issue by ArcherFMY** [IceTTTb/PlaneTR3D#4]
Hi,

Thank you for such a great job!

I have troubles when downloading the `planes_scannet_train.tfrecords` from the [link](https://drive.google.com/file/d/1NyDrgI02ao18WmXyepgVkWGqtM3YS3_4/view) provided by [PlaneNet](https://github.com/art-programmer/PlaneNet). I just could not download the data. Another [box link](https://wustl.box.com/s/d3vmtei5sin40svky6dcbe2aqhh5tmoz) does not work (the file has been removed). So would you mind sharing your downloaded .tfrecords or preprocessed .npz files? Thanks a lot!

**Comment by IceTTTb** [comment]
Hi,

Sorry for the late reply.

The link of the planes_scannet_train.tfrecords provided by PlaneNet seems available now. Maybe you can try to download it again. Please let me know if you successfully download the data.

**Comment by ArcherFMY** [comment]
Thanks a lot! I have successfully downloaded the data from the [google drive](https://drive.google.com/file/d/1NyDrgI02ao18WmXyepgVkWGqtM3YS3_4/view)

**Comment by zhang-21** [comment]
@IceTTTb 
Hi,
Thanks for your great work!
I can't completly download the file named `planes_scannet_train.tfrecords` too. So, could you please share the training file in somewhere like BaiduDisk?

**Comment by zzh-whu-pixel** [comment]
Hi @RenQJ,

Sorry to revisit this old issue. I noticed that you mentioned that you had successfully downloaded the dataset.

I am specifically looking for the original PlaneNet ScanNet dataset:

- `planes_scannet_train.tfrecords`
- `planes_scannet_val.tfrecords`

or the complete PlaneAE `.npz` dataset converted from these TFRecord files.

The original Google Drive, Box, and other mirror links are no longer accessible. Do you still have a copy of the dataset? If convenient, could you please share it through Baidu Netdisk, Google Drive, OneDrive, or another temporary link?

The dataset will only be used for academic research and reproducibility.

My email is: `zzh6466@gmail.com`

Thank you very much.
