### ISSUE TITLE
Number of lines

### ISSUE THREAD

**Issue by zhirui-gao** [IceTTTb/PlaneTR3D#5]
您好！请问对于直线检测阶段，对于不同的图片，检测的是处理成了固定数量的吗？这个数量设的是多少？

**Comment by cherubicXN** [comment]
plz read our paper

**Comment by IceTTTb** [comment]
Hi,

We set the length of line segment sequence as 200. If the number of detected line segments is fewer than 200, we pad it to 200 with zeros.
