### ISSUE TITLE
Looking for train.txt and val.txt

### ISSUE THREAD

**Issue by yq-Liang** [IceTTTb/PlaneTR3D#6]
Congratulations on great work !
I am just looking for two files named train.txt and val.txt but failed. Could you please tell me where i can get them or the details of them?
Thanks a lot.

**Comment by IceTTTb** [comment]
@yq-Liang Thanks for your interest in our work. These two files (train.txt and val.txt) are created by planeAE with 'convert_tfrecords.py'. Please refer to the 'Downloading and converting data' part in [planeAE](https://github.com/svip-lab/PlanarReconstruction).

**Comment by yq-Liang** [comment]
Got it! Thank you~
