### ISSUE TITLE
Some evaluation results of planeTR (no line segments) model is different from that in your paper？

### ISSUE THREAD

**Issue by SJingjia** [IceTTTb/PlaneTR3D#7]
Hi，
I modified “config_planeTR_train.yaml”, set model.use_lines=False, model.loss_layer_num=1, and other items remained unchanged.  After training, I evaluated the model and found that per-plane/pixel recalls with small error thresholds was very different from that in your paper.  As shown in the pictures below.

![image](https://user-images.githubusercontent.com/28842290/218249187-ec86b87d-5d8b-46cf-b870-f4f3a0481419.png)
![image](https://user-images.githubusercontent.com/28842290/218249205-527efce0-064f-4abb-acbf-79cb18e3f407.png)

Do you know the reason?  Is there any other training configuration to be modified?

Thanks！

**Comment by IceTTTb** [comment]
Hi @SJingjia 
The results without line segments in Table 3 are achieved by retraining a model without line segments (set model.use_lines=False).

**Comment by SJingjia** [comment]
> Hi @SJingjia The results without line segments in Table 3 are achieved by retraining a model without line segments (set model.use_lines=False).

Hi, when I set only model.use_lines=False, the following prompt appears:

=> loading pretrained model ckpts/hrnetv2_w32_imagenet_pretrained.pth

********************

dataloader: predict_center =  True
/home/xxx/anaconda3/envs/xxx/lib/python3.7/site-packages/torch/_tensor.py:575: UserWarning: floor_divide is deprecated, and will be removed in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values.
To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor'). (Triggered internally at  /opt/conda/conda-bld/pytorch_1623448265233/work/aten/src/ATen/native/BinaryOps.cpp:467.)
  return torch.floor_divide(self, other)
Traceback (most recent call last):
  File "train_planeTR.py", line 314, in <module>
    train(cfg, logger)
  File "train_planeTR.py", line 206, in train
    outputs = network(image, lines, num_lines)
  File "/home/jingjia/anaconda3/envs/planeformer/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jingjia/workplace/PlaneTR3D/models/planeTR_HRNet.py", line 348, in forward
    assert plane_prob.shape[0] == 2
AssertionError

**Comment by IceTTTb** [comment]
Hi, @SJingjia 
I'm sorry that I misunderstood your original question.  Set model.use_lines=False, model.loss_layer_num=1, and other items remaining unchanged in the training stage of the no line segments model is correct. Did you also set model.use_lines=False in the evaluation stage?

**Comment by SJingjia** [comment]
Yes! This is because I forgot to set False in the evaluation stage, thanks!
